version: '3.9'

services:
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0708
      - POSTGRES_DB=products_management
    volumes:
      - ./create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
  api_express:
    container_name: api
    image: api_express
    build: .
    ports:
      - 3333:3333
    depends_on:
      - db
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=0708
      - DB_HOST=db
      - DB=products_management
      - DB_PORT=5432
